yyl1.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl2.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl3.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl4.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl5.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl6.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl7.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl8.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl9.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl10.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl11.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl12.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl13.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl14.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl15.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl16.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl17.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl18.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl19.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl20.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl21.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl22.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl23.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl24.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl25.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl26.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl27.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl28.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl29.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1

yyl30.in:
  timeLimit: 2000
  memoryLimit: 512000
  score: 1